### ISSUE TITLE
unknown issue for .exe

### ISSUE THREAD

**Issue by HWR-llc** [dsi-llc/EFDCPlus#2]
Compile appears successful:
```
1>EFDCPlus_MPI_10.4.0 - 0 error(s), 350 warning(s)
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
But if I try to run the .exe file, I get this error:
![image](https://user-images.githubusercontent.com/10170000/150849442-0895c579-44f2-4608-9982-d9d747d0f526.png)

It could be related to netCDF fix in #1 if I have the wrong netCDF version, but really I have no idea. 

I can send the buildLog.htm if that's helpful.

Any help you can provide, would be greatly appreciated.

**Comment by perspicacious-one** [comment]
If you extract these files into wherever your efdc executable is, are you then able to run efdc? What command structure are you using for running efdc?
[depend.zip](https://github.com/dsi-llc/EFDCPlus/files/7928371/depend.zip)

**Comment by HWR-llc** [comment]
Yes, that worked. 

To run EFDC, I just open a command window, navigate to the appropriate directory and type:
`EFDCPlus_MPI_10.4.0.exe`

**Comment by mishranurag** [comment]
Matt

If you ran the model using this compiled executable, please email sales@eemodelingsystem.com, and claim your free gifts.

Sincerely
~Anurag

**Comment by HWR-llc** [comment]
I don't want to take credit yet. I have not successfully run a model. I think I may have found a bug, or it may just be an error within the input files. I'm trying to run the [DM-14_Lake_T_HYD-WQ_Model_(EE10.2) ](https://www.eemodelingsystem.com/hands-on-tutorials). EFDCPlues begins to run, but then says:
```
SCANNING INPUT FILE: DECOMP.JNP
forrtl: severe (29): file not found, unit 21, file C:\XXX\DM-14_Lake_T_HYD-WQ_Model_(EE10.2)\Models\Hyd\decomp.jnp
```
There is no .jnp file in the directory. I changed the extension for the decomp file from .inp to .jnp and it finds the file. Then I get an EFDC error:
```
SCANNING INPUT FILE: DECOMP.JNP
SCANNING INPUT FILE: EFDC.INP
SCANNING INPUT FILE: QSER.INP
ALLOCATING ARRAYS
INITIALIZING REAL ARRAYS
INITIALIZING INTEGER ARRAYS
READING THE MAIN EFDC CONTROL FILE: EFDC.INP
DEBUG OFF

READ ERROR FROM FILE EFDC.INP ON CARD 14

EFDCPlus Stopped: SEE #OUTPUT\EFDC_LOG.OUT FOR MORE INFORMATION
Fortran Pause - Enter command<CR> or <CR> to continue.
```
I'm more used to those types of errors. I assume that is an issue specific to the example model, not the modeling software. Do you know if that example model is free from errors?

**Comment by perspicacious-one** [comment]
@HWR-llc ,
We've updated the model files and included them in this release: https://github.com/dsi-llc/EFDCPlus/releases/tag/v10.4.0-beta
