### ISSUE TITLE
ReadMe.md file errors

### ISSUE THREAD

**Issue by ambfp** [dsi-llc/EFDCPlus#3]
Hello,
The ReadMe.md file have very simple errors that affect linux compilation.

- _chmod -x toolkit-setup.sh_ must be _chmod +x toolkit-setup.sh_;
- _chmod -x efdc.x_ must be _chmod +x efdc.x_

Thank you. Regards. Fernando.

**Comment by perspicacious-one** [comment]
Fixed. Thank you for pointing that out.
