### ISSUE TITLE
Compiling error with NCOUT

### ISSUE THREAD

**Issue by westdata** [dsi-llc/EFDCPlus#3]
**Describe the bug**
When the conditional compilation option "NCOUT" is open, the compiler is giving the following error:
error #7881: This module file was generated for a different platform or by an incompatible compiler or compiler release. It cannot be read.   [NETCDF]		E:\EFDCPlus-master\EFDC\mod_netcdf.f90	7	

**To Reproduce**
1. Use Visual Studio 2015 to open the EFDCPlus_085_OMP.sln
2. Go to Project-Properties-Fortran-General-Preprocessor Defination, Add "NCOUT"
2. In "Additional Include Directories", type "..\NetCDFLib\include"
3.Compile the project
4. See errors

**Expected behavior**
There are many errors, one of which is "error #7881: This module file was generated for a different platform or by an incompatible compiler or compiler release".

**Screenshots**
See the screenshots.

![screenshot1](https://user-images.githubusercontent.com/17287144/89482467-8ef5e000-d7cc-11ea-9573-6379f59ed438.png)
![screenshot2](https://user-images.githubusercontent.com/17287144/89482478-95845780-d7cc-11ea-9d49-e0e99a75c8ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Visual Studio 2015
 - Fotran Compiler: Intel Parallel Studio XE 2018 Update 4

**Comment by perspicacious-one** [comment]
Unfortunately we can't provide assistance with environment setup and build issues. However you might find this helpful...

https://www.eemodelingsystem.com/efdc-insider-blog/compile-efdc-source-code-using-intel-oneapi
